---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: immich

resources:
- ./metrics-exporter.yaml
- ./scrape.yaml

secretGenerator:
- name: metrics-api-key
  envs:
  - ./env/api-key.env

patches:
- target:
    kind: ScrapeConfig
    name: immich-statistics
  path: ./env/patch-location-tag.yaml
- target:
    kind: ScrapeConfig
    name: immich-statistics
  path: ./env/patch-immich-cluster-tag.yaml
