
name: intel-gpu-plugin

image:
  hub: intel
  tag: ""

initImage:
  enable: false
  hub: intel
  tag: ""

sharedDevNum: 5
logLevel: 2
resourceManager: false
enableMonitoring: true
allocationPolicy: "none"

nodeSelector:
  intel.feature.node.kubernetes.io/gpu: 'true'

tolerations:

nodeFeatureRule: true
